language: python
python:
  - "2.7"
 
install:
    - pip install -r requirements.txt
    - pip install pytest-cov
    - pip install coveralls
    
script: python -m pytest -v -x --cov=stylecheck

after_success:
    - coveralls
