language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
 
install:
    - pip install -r requirements.txt
    - pip install pytest-cov
    - pip install coveralls
    
script: python -m pytest -v -x --cov=stylecheck

after_success:
    - coveralls
      
branches:
  only:
    - master
